name: 'Delete oldest runs for workflow'
description: 'An action to delete the oldest runs for a specific workflow and other than a specific minimum number of runs.'
author: 'Matt Wiggins'

inputs:
  token:
    description: 'The token used to authenticate.'
    required: true
    default: ${{ github.token }}

  repository:
    description: 'The name of the repository.'
    required: true
    default: ${{ github.repository }}

  workflow_name:
    description: 'The name of the workflow'
    required: true
    default: ""

  keep_minimum_runs:
    description: 'The minimum runs to keep for each workflow.'
    required: true
    default: 6

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'delete'
  color: 'red'
